services:
  database:
    image: mariadb:11
    restart: always
    environment:
      - MARIADB_DATABASE=sincrm4beta
      - MARIADB_USER=xas
      - MARIADB_PASSWORD=79eagle
      - MARIADB_ROOT_PASSWORD=root_pass_placeholder
    volumes:
      - sincrm-db-data:/var/lib/mysql
      - ./database/backup:/docker-entrypoint-initdb.d:ro
    networks:
      - sincrm-network

  app:
    build: .
    restart: always
    depends_on:
      - database
    volumes:
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - DB_HOST=database
      - DB_USER=xas
      - DB_PASS=79eagle
      - DB_NAME=sincrm4beta
    expose:
      - 80
    networks:
      - sincrm-network
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sincrm-beta.rule=Host(`beta.pedrodiaz.eu`)"
      - "traefik.http.routers.sincrm-beta.entrypoints=web"
      - "traefik.http.services.sincrm-beta.loadbalancer.server.port=80"
      - "traefik.docker.network=coolify"

networks:
  sincrm-network:
  coolify:
    external: true

volumes:
  sincrm-db-data:
