services:
  database:
    image: mariadb:11
    container_name: sincrm-beta-db
    restart: always
    environment:
      - MARIADB_DATABASE=sincrm4beta
      - MARIADB_USER=xas
      - MARIADB_PASSWORD=79eagle
      - MARIADB_ROOT_PASSWORD=root_pass_placeholder
    volumes:
      - sincrm-db-data:/var/lib/mysql
      - ./database/backup/latest_migration_backup.sql.gz:/docker-entrypoint-initdb.d/backup.sql.gz:ro
    networks:
      - sincrm-network

  app:
    build: .
    container_name: sincrm-beta-app
    restart: always
    depends_on:
      - database
    volumes:
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - DB_HOST=database
      - DB_USER=xas
      - DB_PASS=79eagle
      - DB_NAME=sincrm4beta
    expose:
      - 80
    networks:
      - sincrm-network

networks:
  sincrm-network:
    name: sincrm-network

volumes:
  sincrm-db-data:
